management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  profiles:
    active: dev
  application:
    name: ny-cloud-gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848   #nacos ip:port
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
