server:
  port: 84

spring:
  application:
    name: account-service
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719

  servlet:
    multipart:
      max-file-size: 10MB

management: #sentinel配置监控
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ny.springcloud.entities  # 所有Entity 别名类所在包

feign: #远程服务接口openfeign调用配置
  client:
    config:
      default:
        connectTimeout: 5000 #连接超时
        readTimeout: 5000 #读取超时
        loggerLevel: full


seata:
  tx-service-group: my_tx_group #seata配置文件里的配置