server:
  port: 8000

spring:
  application:
    name: boot-admin
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #metadata:
          #user.name: user
          #user.password: password
  #security:
    #user:
      #name: "user"
      #password: "password"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

